#added to trigger build
# adding another comment to trigger build

sudo: required
services:
  - docker

before_install: 
  - docker build -t aykaytee/docker-react -f ./Dockerfile.dev .

script:
  - docker run -e CI=true aykaytee/docker-react npm run test

